Hometask for lec6
AlesiaRebkavets/Hometask_Lec5 pull request #2
Opened 2022-11-10 08:34 UTC by AlesiaRebkavets

2022-11-14 07:30 UTC, ezhukovskaya requested changes

2022-11-14 07:30 UTC, ezhukovskaya commented on Worker/Person.cs
> +        private Boolean poluchilPovestku;
not Boolean, use simple call for 'bool'

2022-11-14 07:30 UTC, ezhukovskaya commented on Factory/FactoryWorkers.cs
> +    public static Person[] ArrayElementInitialization(byte numberOfArrayElements, string name, string lastName, byte age, char sex, byte skillLevel, byte absenseFromWorkInDays, Boolean fired, Boolean
bool instead of Boolean

2022-11-14 07:30 UTC, ezhukovskaya commented on Factory/FactoryWorkers.cs
> +            a[i] = new Person(name, lastName, age, sex, skillLevel, absenseFromWorkInDays, fired, poluchilPovestku);
for example I want to add 7 workers, so there's gonna be 7 workers with the same name and etc.?

2022-11-14 07:30 UTC, ezhukovskaya commented on Factory/FactoryWorkers.cs
> +    public static void OuptufOfArayLength(String displayedComment, Person[] a)   // output an array length (number of workers)
string, not String

2022-11-14 23:13 UTC, AlesiaRebkavets commented on Worker/Person.cs
> +        private Boolean poluchilPovestku;
corrected

2022-11-14 23:15 UTC, AlesiaRebkavets commented on Factory/FactoryWorkers.cs
> +    public static Person[] ArrayElementInitialization(byte numberOfArrayElements, string name, string lastName, byte age, char sex, byte skillLevel, byte absenseFromWorkInDays, Boolean fired, Boolean
corrected

2022-11-15 00:35 UTC, AlesiaRebkavets commented on Factory/FactoryWorkers.cs
> +            a[i] = new Person(name, lastName, age, sex, skillLevel, absenseFromWorkInDays, fired, poluchilPovestku);
Этой частью кода показала, что умею использовать конструктор. Далее используются геттеры и сеттеры. В BaseClass оставляла комментарий на этот счет.

2022-11-15 00:36 UTC, AlesiaRebkavets commented on Factory/FactoryWorkers.cs
> +    public static void OuptufOfArayLength(String displayedComment, Person[] a)   // output an array length (number of workers)
corrected

2022-11-17 06:59 UTC, ezhukovskaya approved these changes

2022-11-18 21:07 UTC, merged